import type {NextPage} from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-3xl font-bold underline text-red-500">
          This is my content
        </div>
      </main>
    </div>
  );
};

export default Home;
