import Header from '@components/Header';
import {getMdxData} from '@utils/get-mdx-content';
import type {NextPage} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import {useEffect} from 'react';

const Home: NextPage<any> = ({contents}) => {
  useEffect(()=>{
    console.log(contents);
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='p-5 flex justify-center'>
        <div className='container flex items-center flex-col'>
          <h2 className='text-5xl font-light text-neutral-700'>Hello Cheater</h2>
          <h3 className='my-5'>This content for you</h3>
          <div className='flex w-full px-20 mt-5'>
            {Object.entries(contents).map(([category, content]:any, index)=>{
              return (
                <div className='basis-1/2' key={index}>
                  <h2 className='text-xl text-sky-700'>{category}</h2>
                  <ul className='list-disc pl-5 pt-2'>
                    {content.map(({slug, data}:any)=>{
                      return (
                        <li key={slug}>
                          <Link href={slug}>
                            <a className='hover:text-sky-900'>
                              {data.title}
                            </a>
                          </Link>
                          {data.version && (
                            <a href={data.versionLink} className='cursor-pointer text-yellow-500 ml-5 hover:underline'>
                              [{data.version}]
                            </a>
                          )}
                          {data.language &&(
                            <span className='text-sm text-green-300 ml-2'>({data.language})</span>
                          )}
                        </li>
                      );
                    })}
                  </ul>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps({params}:any) {
  const posts = await getMdxData('data');

  const contents = posts.reduce((acc: any, item, index)=>{
    const category = item.data.category;

    if (!acc[category]) {
      acc[category] = [];
    }

    acc[category].push(item);
    return acc;
  }, {});

  return {
    props: {
      contents,
    },
  };
}


export default Home;
